### PR TITLE
Osram Smart+ Plug

### PR DESCRIPTION
**Pull request by BobbyT**
Added support for Osram Smart+ Plug.

Who wants to test?

### CODE REVIEW

**Comment by juancpin** [comment]
Just to know: Do I need a hub to connect this? Or will it connect through an app, and then be controllable with Homekit? (like webosTVs or Broadlink RMs?)

Thanks!! 

(update: I think I need a hub... don't like)

**Comment by BobbyT** [comment]
Yes, some kind of a hub/gateway. In this case homebridge with zigbee. I have a Raspberry Pi running hombebridge, where the smart plugs are registered. The iOS Home app can access homebrdige.

But you can use an App

**Comment by Olepir** [comment]
> Added support for Osram Smart+ Plug.

Can you add some other devices?

**Comment by BobbyT** [comment]
@Olepir what kind? I would need the zigbee.db and some one to test...

**Comment by Olepir** [comment]
> @Olepir what kind? I would need the zigbee.db and some one to test...

I can send you zigbee.db and test it. Where to send?

**Comment by BobbyT** [comment]
@Olepir open issue, I will try and create a branch which can be tested

**Pull request closed without merging**
